#!/bin/bash

# variables
uptime="$(uptime -p | sed -e 's/up //g')"
shutdown='󰐥'
reboot='󰜉'
lock=''
logout='󰍃'
yes='󰸞'
no='󱎘'

rofi_cmd() {
	rofi -dmenu \
		-p "Uptime: $uptime" \
		-mesg "Uptime: $uptime" \
		-theme ~/.config/rofi/powermenu/style.rasi
}

confirm_cmd() {
	rofi -theme-str 'window {location: center; anchor: center; fullscreen: false; width: 350px;}' \
		-theme-str 'mainbox {children: [ "message", "listview" ];}' \
		-theme-str 'listview {columns: 2; lines: 1;}' \
		-theme-str 'element-text {horizontal-align: 0.5;}' \
		-theme-str 'textbox {horizontal-align: 0.5;}' \
		-dmenu \
		-p 'Confirmation' \
		-mesg 'Are you sure?' \
		-theme ~/.config/rofi/powermenu/style.rasi
}

confirm_exit() {
	echo -e "$yes\n$no" | confirm_cmd
}

run_rofi() {
	echo -e "$lock\n$logout\n$reboot\n$shutdown" | rofi_cmd
}

# Execute Command
run_cmd() {
	selected="$(confirm_exit)"
	if [[ "$selected" == "$yes" ]]; then
		if [[ $1 == '--shutdown' ]]; then
			# systemctl poweroff
			shutdown -h now
		elif [[ $1 == '--reboot' ]]; then
			# systemctl reboot
			reboot
		elif [[ $1 == '--logout' ]]; then
			i3-msg exit
		elif [[ $1 == '--lock' ]]; then
			# i3lock -i ~/Pictures/wallpaper/wallhaven-e7g71w_1920x1080.png -t -f -e
			i3lock
		fi
	else
		exit 0
	fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
$shutdown)
	run_cmd --shutdown
	;;
$reboot)
	run_cmd --reboot
	;;
$lock)
	run_cmd --lock
	;;
$logout)
	run_cmd --logout
	;;
esac
